### ISSUE TITLE
Propunere

### ISSUE THREAD

**Issue by witalik93** [wanoo21/radiosmoldova#1]
Salutare. Îți scriu cu o mulțumire pentru aplicația oferită de tine. Apreciez eforturile tale și aș veni cu o propunere, bineînțeles nu e nimic mai mult decât atât și nici măcar nu ești obligat să îndeplinești ceea ce te voi ruga. Deci, propunerea mea este următoarea: vreau să aflu dacă ești dispus să creezi o aplicație similară cu posturi de radio din românia sau să vii cu completări de posturi românești ale aplicației actuale. Sunt foarte multe persoane printre care și eu care și-ar dori o listă cu posturi românești. Mersi și spor în ceea ce faci.

**Comment by wanoo21** [comment]
Salutare, multumesc mult pentru apreciere si propunere, aveam si eu aceasta idee atunci cind am lansat aplicatia, insa cu timpul si cu taote ce sunt de facut am si uitat :) sigur ca o pot face si o voi face, in citeva zile va aparea in Magazinul web Chrome. Trebuie doar sa ma gindesc, sa o fac aparte, sau sa completez  lista actuala, si sa le impart in doua categorii, inca nustiu cum e mai bine, in tot cazul am sa scriu tot aici un comentariu toate dealiile!
Multumesc mult inca odata.

**Comment by wanoo21** [comment]
Iata si rezultatul https://chrome.google.com/webstore/detail/radio-romania/hhnllbiimihbjlmcfbbddfcmpgpeklfk

**Comment by witalik93** [comment]
Ms Mult :) Ai făcut o treabă bună.
